import type { Metadata } from "next";
import { Inter, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollToTop from "./components/ScrollUpBtn";

// Import Inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Import Bebas Neue
const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400", // Bebas Neue biasanya satu weight aja (regular)
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SR Point Cars | Nano Detailing Mobil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${inter.variable} ${bebasNeue.variable} antialiased font-inter`}
      >
        <Navbar />
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
